### ISSUE TITLE
Cant get it running 

### ISSUE THREAD

**Issue by yossi-eynav** [omrilotan/apparatus#4]
@omrilotan 
I'm using this sheet- https://docs.google.com/spreadsheets/d/e/2PACX-1vT_qmFIRC_T2wgp2sqmbRizz21K_HXLT2pGxxl2kLovi5QJ-7PJMcIqqS23vRL-m3xZTqUS0rE1D9q5/pubhtml 

getting error while parsing it (server is returning 400 ).
Am I missing something?

**Comment by yossi-eynav** [comment]
![image](https://user-images.githubusercontent.com/8016250/53009098-6a287400-3443-11e9-8fc0-1a53148d7225.png)

**Comment by omrilotan** [comment]
Did you publish to the web (and checked the "Automatically republish" checkbox)?

| ![](https://user-images.githubusercontent.com/516342/53014404-0f961480-3451-11e9-9716-31a90eb38f65.png) | ![image](https://user-images.githubusercontent.com/516342/53014428-22104e00-3451-11e9-8165-66c3762634e7.png)
| - | -

**Comment by yossi-eynav** [comment]
@omrilotan Yes

**Comment by omrilotan** [comment]
Okay. Thanks for the issue. I'll try to get into it tonight

**Comment by omrilotan** [comment]
> Update
Seems like the JSON format availability changed.
https://spreadsheets.google.com/feeds/list/2PACX-1vT_qmFIRC_T2wgp2sqmbRizz21K_HXLT2pGxxl2kLovi5QJ-7PJMcIqqS23vRL-m3xZTqUS0rE1D9q5/od6/public/basic?alt=json
I'll have to look into what is the new URL scheme. Another day tho
